config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resource :user do
    scope module: 'users' do
      resource :location
      resource :gender
    end
  end

  resources :schedules
  resources :conversations do
    resources :messages
  end

  resources :matches

  get "sessions/destroy"

  controller :sessions do
  get 'logout' => :destroy  
  end

  # Defines the root path route ("/")
  root "homepage#index"
  get "dashboard", to: "dashboard#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user_1, class_name: 'User'
  belongs_to :user_2, class_name: 'User'
  has_many :messages

  def name(user)
    user_1 == user ? user_2.first_name : user_1.first_name
  end

  def increment_unread(user)
    if user_1 == user
      update(unread_for_user_2: unread_for_user_2.to_i + 1)
    else
      update(unread_for_user_1: unread_for_user_2.to_i + 1)
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :conversation
end

app/models/removed_match.rb
class RemovedMatch < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :availability, :location, :gender, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable,
  devise :omniauthable, omniauth_providers: %i[linkedin]
  
  has_many :schedules, dependent: :destroy

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.linkedin_data'] && session['devise.linkedin_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture_url = auth.info.picture_url
    end
  end

  def matches
    Schedule
      .from('schedules AS other_schedules')
      .joins('INNER JOIN schedules self_schedules ON self_schedules.availability = other_schedules.availability AND self_schedules.location = other_schedules.location AND self_schedules.user_id <> other_schedules.user_id')
      .order('other_schedules.availability, other_schedules.location')
      .where.not('other_schedules.user_id': id)
      .where('self_schedules.user_id': id)
      .where('other_schedules.gender': gender)
      .where('other_schedules.availability >= ?', Date.today)
      .where('NOT EXISTS(SELECT 1 FROM removed_matches WHERE removed_matches.schedule_1_id = self_schedules.id AND removed_matches.schedule_2_id = other_schedules.id)')
      .where('NOT EXISTS(SELECT 1 FROM removed_matches WHERE removed_matches.schedule_1_id = other_schedules.id AND removed_matches.schedule_2_id = self_schedules.id)')
      .select('other_schedules.*, self_schedules.id AS self_schedule_id')
  end

  def unread
    Conversation.where(user_1: self).pluck(:unread_for_user_1).compact.sum +
      Conversation.where(user_2: self).pluck(:unread_for_user_2).compact.sum
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    return edit_user_location_path if resource.location.blank?
    return edit_user_gender_path if resource.gender.blank?

    dashboard_path
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = Conversation.where(user_1_id: current_user.id).or(Conversation.where(user_2_id: current_user.id))
  end

  def new
    @conversation = Conversation.create(user_1_id: current_user.id, user_2_id: params[:recipient_id])
    
    redirect_to conversation_path(@conversation)
  end

  def show
    @conversations = Conversation.where(user_1_id: current_user.id).or(Conversation.where(user_2_id: current_user.id))
    @conversation = Conversation.find(params[:id])
    @message = Message.new
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @matches = current_user.matches.group_by { |m| "#{m.availability} #{m.location}" }
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
      redirect_to root_path
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def destroy
    RemovedMatch.create(
      schedule_1_id: params[:id],
      schedule_2_id: params[:self_schedule_id]
    )

    redirect_to '/dashboard'
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @conversation = Conversation.find(params[:conversation_id])
    @conversation.increment_unread(current_user)
    @message = @conversation.messages.create(message_params)

    redirect_to conversation_path(@conversation)
  end

  private

  def message_params
    {
      author: current_user,
      content: params[:message][:content]
    }
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!

  def index
    @schedules = current_user.schedules
  end

  def new
    @schedule = current_user.schedules.new
    @schedule = Schedule.new(params[:schedule])
  end

  def create
    @schedule = current_user.schedules.new
    @schedule.update(schedule_params)

    if @schedule.valid?
      redirect_to dashboard_path
    else 
      render :new, status: 422
    end
  end

  def show
    @schedule.find(schedule_params[:id])
    @schedule.destroy

    redirect_to schedules_path
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    redirect_to schedules_path
  end

  private

  def schedule_params
    params.require(:schedule).permit(:availability, :location, :gender)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users/genders_helper.rb
module Users::GendersHelper
end

app/helpers/users/locations_helper.rb
module Users::LocationsHelper
end

app/views/conversations/index.html.haml
%nav
  .container.border-bottom
    %a.navbar-brand.fw-bold.fs-4 Profile
    %ul.nav.justify-content-center
      %li.nav-item
        %a=link_to 'Matches', dashboard_path, class: 'text-decoration-none mx-2'
      %li.nav-item
        %a= link_to 'Messages', conversation_path(@conversations.first), class: 'text-decoration-none'
        %span.badge.text-bg-secondary= current_user.unread
      %li.nav-item
        %a= link_to 'New Schedule', new_schedule_path, class: 'text-decoration-none mx-2'
      %li.nav-item
        %a= link_to 'Schedules', schedules_path, class: 'text-decoration-none'    
.conversations
  .sidebar.border-end{style: "width:25%"}
    %H4.m-1 Messaging
    %ul.list-group
      - @conversations.each do |conversation|
        %li.list-group-item{class: conversation == @conversation ? 'active' : ''}
          = link_to conversation.name(current_user), conversation_path(conversation), class: 'text-decoration-none'

app/views/conversations/show.html.haml
%nav.border-bottom
  .container
    %a.navbar-brand.fw-bold.fs-4 Profile
    %ul.nav.justify-content-center
      %li.nav-item
        %a=link_to 'Matches', dashboard_path, class: 'text-decoration-none mx-2'
      %li.nav-item
        %a= link_to 'Messages', conversation_path(@conversations.first), class: 'text-decoration-none'
        %span.badge.text-bg-secondary= current_user.unread
      %li.nav-item
        %a= link_to 'New Schedule', new_schedule_path, class: 'text-decoration-none mx-2'
      %li.nav-item
        %a= link_to 'Schedules', schedules_path, class: 'text-decoration-none'
.conversations.h-100.scrollspy-example.bg-light.p-3.rounded-2{"data-bs-root-margin" => "0px 0px -40%", "data-bs-smooth-scroll" => "true", "data-bs-spy" => "scroll", "data-bs-target" => "#navbar-example2", tabindex: "0"}
  .sidebar.border-end{style: "width:25%"}
    %H4.m-1 Messaging
    %ul.list-group
      - @conversations.each do |conversation|
        %li.list-group-item{class: conversation == @conversation ? 'active' : ''}
          = link_to conversation.name(current_user), conversation_path(conversation), class: 'text-decoration-none'
  %div
  .container-messages.d-block.w-100.h-80
    %ul.container
      - @conversation.messages.each do |message|
        %li{class: message.author == current_user ? 'self' : 'other'}
          %p.fs-5= message.content
          %p.fw-lighter= message.created_at.to_formatted_s(:long)
    %div.container
      .form-control.bottomleft
        = form_for [@conversation, @message] do |f|
          %span= f.text_field :content
          %span= f.submit

app/views/schedules/index.html.haml
%nav
  .container
    %a.navbar-brand.fw-bold.fs-4 Profile
    %ul.nav.justify-content-center
      %li.nav-item
        %a=link_to 'Matches', dashboard_path, class: 'text-decoration-none mx-2'
      %li.nav-item
        %a=link_to 'Messages', conversations_path, class: 'text-decoration-none mx-2'
      %li.nav-item
        %a= link_to 'New Schedule', new_schedule_path, class: 'text-decoration-none mx-2'
      %li.nav-item
        %a= link_to 'Schedules', schedules_path, class: 'text-decoration-none'   
%table
  %thead
    %th Availability
    %th Location
    %th Gender-Preference
  %tbody
    - @schedules.each do |schedule|
      %tr
        %td= schedule.availability
        %td= schedule.location
        %td= schedule.gender
        %td= link_to 'X', schedule, data: { turbo_method: :delete }

app/views/schedules/new.html.haml
%nav
  .container
    %a.navbar-brand.fw-bold.fs-4 Profile
    %ul.nav.justify-content-center
      %li.nav-item
        %a=link_to 'Matches', dashboard_path, class: 'text-decoration-none mx-2'
      %li.nav-item
        %a=link_to 'Messages', conversations_path, class: 'text-decoration-none mx-2'
      %li.nav-item
        %a= link_to 'New Schedule', new_schedule_path, class: 'text-decoration-none mx-2'
      %li.nav-item
        %a= link_to 'Schedules', schedules_path, class: 'text-decoration-none'   

- if @schedule.errors.any?
  #error-explanation
    %p.text-danger #{pluralize(@schedule.errors.count, 'error')} prohibited this article from being saved:
    %ul
      - @schedule.errors.each do |error|
        %li.text-danger.fst-italic= error.full_message

.form-group
  = form_for @schedule do |f|
    %p.mb-1= f.label :availability
    = f.date_field :availability
    %p.mb-1= f.label :location
    = f.text_field :location
    %p.mb-1= f.label :gender
    = f.text_field :gender
    %p.mt-5= f.submit 